### ISSUE TITLE
General Starter.php Calismiyor

### ISSUE THREAD

**Issue by burakbuylu** [tkaratug/titan2#11]
Örneğin bir classımız olsun mesela reCaptcha;
new reCaptcha;

bu class'ı her sayfada başlatmak yerine bir start.php dosyamız olsa laraveldeki starter gibi;

$class = new reCaptcha($input,$secret);

orada class ı başlatıp ayarlarımızı girsek ?

Veya; $template = config('App.general.template');

versek global bir template değişkeni olsa hocam ?  veya var ben mi göremedim

**Comment by zeydo** [comment]
System içinde bir controller var aslında kütüphaneyi orada başlatıp diğer controller ondan extends olursa iş görür diye düşünüyorum. Geçmişte bende bu sorundan muzdariptim Controllers dizininden base controller oluşturup diğer controlleri bundan extends etmiştim. Ama dediğiniz olayda güzel.

**Comment by tkaratug** [comment]
Harici kütüphanelerin entegrasyonu ile ilgili aşağıdaki dökümanı inceleyebilirsiniz;
[http://v2.titanphp.com/doc/external](url)
