### ISSUE TITLE
Render ile HTML Entitiy Edilerek Gönderiliyor

### ISSUE THREAD

**Issue by burakbuylu** [tkaratug/titan2#14]
View::render($tpl,$var);

yaptığımız vakit $var değerinde HTML varsa eğer entity yapıyor değeri;

Örneğin; Pagination::printLinks() bastığımızda edge tamamen aralara quot atarak veriyor

`&lt;ul class=&quot;pagination&quot;&gt;&lt;li class=&quot;active&quot;&gt;&lt;a href=&quot;/backend/series/?page=1&quot;&gt;1&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;/backend/series/?page=2&quot;&gt;2&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;/backend/series/?page=3&quot;&gt;3&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;/backend/series/?page=4&quot;&gt;4&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;/backend/series/?page=5&quot;&gt;5&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;/backend/series/?page=6&quot;&gt;6&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;/backend/series/?page=7&quot;&gt;7&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;/backend/series/?page=8&quot;&gt;8&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;/backend/series/?page=9&quot;&gt;9&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;span&gt;...&lt;/span&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;/backend/series/?page=55&quot;&gt;55&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;/backend/series/?page=2&quot;&gt;Next &amp;raquo;&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;`

**Comment by tkaratug** [comment]
view dosyasına yazdıracağınız datanın escape edilmesini istemiyorsanız `{!! $data !!}` şeklinde kullanmalısınız.
