### ISSUE TITLE
Pagination setLiClass İşlevsellik Göstermiyor

### ISSUE THREAD

**Issue by burakbuylu** [tkaratug/titan2#15]
System\Libs\Pagination\Pagination.php 

363. satırda 

$this->liClass belirtilmemiş

**Comment by tkaratug** [comment]
48. ve 439. satırlarda belirtilmiş.

**Comment by burakbuylu** [comment]
geliştirmeden dolayı satırı hatalı yazmışım prev next için belirtilmemiş o kısım için bahsetmiştim tamamdır buda kafi teşekkürler
