### ISSUE TITLE
Request Post Array Filter

### ISSUE THREAD

**Issue by burakbuylu** [tkaratug/titan2#19]
\System\Libs\Http\Request.php

Array içeren bir post atıldığında trim() fonksiyonu hata veriyor hocam örneğin; name="veri[1]" gönderildiği vakit hata çıkıyor.

506. ; (array map yaparak direk içeriğide temizlenebilir ben bu şekil bi çözüm ürettim)
return ($filter === true) ? $this->xssClean($data) : ((!is_array($data)) ? trim($data) : $data);

**Comment by tkaratug** [comment]
Düzeltildi. [85ea7d9](https://github.com/tkaratug/titan2/commit/85ea7d939dbad27d78f68feaa6bc6fdf8ca162b3)
