### ISSUE TITLE
Image Library Error

### ISSUE THREAD

**Issue by burakbuylu** [tkaratug/titan2#21]
Örnek kullanım ;
```
$imageName = 'upload/series/poster/warehouse.jpg';
Image::load($imageName)->resize(600, 886, 'crop')->save($imageName);
```

Call to a member function resize() on boolean;

İşlevsel kullanım hata veriyor lakin;

            Image::load($imageName);
            Image::resize(600, 886, 'crop');
            Image::save($imageName);

            Image::load($imageName);
            Image::resize(305, 450, 'crop');
            Image::save($imageDir . 'thumb' . DS . $filename);

gittiğimizde ise _outputImage fonksiyonu hata veriyor onada şöyle bir çözüm ürettim;
_outputImage fonksiyonu içeriisndeki ilk satıra public path tanıttım tekrar;
         $destination = public_path($destination);

public function show() içerisinde return $false; yer alıyor hatalı

->save() yaptığımızdada; mevcut dosyayı kontrol ediyor varmı yokmu diye; lakin mevcut dosya yoksa biz yeni kayıt yapmak istiyorsak oraya? o vakit hata veriyor.

Dipnot (Ubuntu sistemimi yedekleyeceğim diskimde arıza olduğundan dolayı bitbucket projemden ötürü git push yapamıyorum düzeldiğinde desteğimi sunacağım şimdilik sizden rica ediyorum 👍 azda olsa destek olabiliyorsak ne ala );

**Comment by tkaratug** [comment]
return $false düzeltildi. [85ea7d9](https://github.com/tkaratug/titan2/commit/85ea7d939dbad27d78f68feaa6bc6fdf8ca162b3)
