### ISSUE TITLE
Router Middleware Sorunu

### ISSUE THREAD

**Issue by burak2yilmaz** [tkaratug/titan2#22]
Merhaba,

Route tanımlamaları yapınca en üstteki Routeye ne middleware atarsam ondan sonra gelenlerde etkileniyor.

`Route::middleware(["Auth"])->get("deneme", function(){
    echo "deneme";
});

Router::get("deneme2", function(){
    echo "deneme2";
});`

Üsttekine Auth middleware'ı atıyorum. Altta ki de etkileniyor.

**Comment by tkaratug** [comment]
Şu anda router kütüphanesinde middleware kullanımı yalnızca rota gruplarında tanımlanabiliyor. Yani tek bir rotaya middleware tanımı yapacaksanız da grup içine almalısınız. Bu durumu ve iç içe gruplandırmayı yapıp yeni sürüme yetiştireceğim.

**Comment by burak2yilmaz** [comment]
Teşekkürler.
