### ISSUE TITLE
Upload filename sorunu

### ISSUE THREAD

**Issue by zeydo** [tkaratug/titan2#25]
Bir dosya upload ettiğimizde  dosyanın adını filename methodu ile değiştirdiğimiz zaman dosya adını tekrar herhangi bir yere yazmak/kayıt etmek istediğimizde erişim mümkün olmuyor ben filename değişkenini public atayarak 
`$dosyaAdi = Upload::filename('yeni_isim.jpg')->filename` 
şeklinde bir kullanım sağladım.
Daha mantıklı ve etkili bir çözümü var mı ?

**Comment by burakbuylu** [comment]
Anladım yapmak istediğinizi şu şekil bi çözüm sunabilirsiniz; hem link olarak size uyarlılık sağlar hem yapı olarak o şekilde ilerlersiniz; file name kısmında ext

$file = Request::file('inputName');
$fileName = basename($file['name']);
$fileNameSef = slug($fileName);
$fileType = strtolower(pathinfo($file,PATHINFO_EXTENSION));

Upload::filename($fileNameSef.'.'.$fileType);
