### ISSUE TITLE
Helper/Route Tek Parametre Çalışmıyor

### ISSUE THREAD

**Issue by burakbuylu** [tkaratug/titan2#26]
Route::get('/products', 'ProductList@Products')->name('products');

route('products');

çalışmıyor; ancak ikincil array parametre gönderirsek çıktı sağlıyor;

route('products',[true]);

**\System\Libs\Router\Router.php@func getUrl(**

parse uri params doluysa verilmiş ondan kaynaklı diye görüyorum net inceleyemedim çözüm olarak şunu yaptım;

```
public static function getUrl($name, $params = [])
to
public static function getUrl($name, $params = [true])
```

**Comment by tkaratug** [comment]
Bilgim var bu konuyla ilgil. dev branch'inde düzelttim diye hatırlıyorum. Yeni sürümde giderilmiş olacak.

**Comment by zeydo** [comment]
Dev ' de düzeltildi bu. geturl fonksiyonundaki if olayı sıkıntı çıkartıyordu
