### ISSUE TITLE
Validation Kütüphanesi - Required problemi.

### ISSUE THREAD

**Issue by OzdemirEmrah** [tkaratug/titan2#3]
Validation sınıfının içerisinde yer alan required fonksiyonu problemli. `empty()` fonksiyonu 0 gönderildiğinde true döndürmekte. 

Bunun için codeigniter'ın required fonksiyonu kullanılabilir. `return is_array($data) ? (empty($data) === FALSE) : (trim($data) !== '');`

**Comment by tkaratug** [comment]
Düzeltildi ve dev branch üzerine push edildi. Teşekkürler.
