### ISSUE TITLE
yeni surum tools Item nedir

### ISSUE THREAD

**Issue by TheYkk** [tkaratug/titan2#31]
yeni surum tools Item nedir ne ise yariyor ne amaci var
kullanimi nasil nerde kullanabiliriz ? 

sorulari cevaplarsaniz sevinirim

**Comment by tkaratug** [comment]
Bir veriyi zincirleme olarak istediğiniz kadar fonksiyondan geçirebiliyorsunuz. Aşağıdaki bağlantıda detaylı anlatım ve örnek görebilirsiniz;
[https://getpocket.com/a/read/1546313554](https://getpocket.com/a/read/1546313554)
