### ISSUE TITLE
View Theme Extend Bug

### ISSUE THREAD

**Issue by burakbuylu** [tkaratug/titan2#39]
Örneğin;
`View::theme('Blue')->render('home', $this->data);`

Ancak extend yaparken tema path'ini tekrar istiyor bizden;

`@extends('Blue/_includes/master')`

Tema içerisinden çekmesi gerekmezmi?
`@extends('_includes/master')`

Bug'mı normal mi bilemedim önerilerinize göre düzeltip push edicem.

**Comment by tkaratug** [comment]
`@extends`, root directory olarak views dizinini gösterir. Bu sebeple çeşitli tema dizinleri içerisinde de buna göre path yazmak gerekiyor. Yaptığım araştırmaya göre sanırım blade için de aynı durum söz konusu.

**Comment by burakbuylu** [comment]
@tkaratug anladım hocam bende blade sistemine baktım şimdi aynı mevzuat yürüyor;
https://laracasts.com/discuss/channels/general-discussion/how-to-implement-view-namespaces-in-l5

mecbur data içerisine template değişkeni verip, tanımlayıp o şekilde calisitiricaz.

Teşekkürler.
