### ISSUE TITLE
Ungroupped Route Problemi

### ISSUE THREAD

**Issue by burakbuylu** [tkaratug/titan2#44]
Yeni güncellemeden sonra eğer rota herhangi bir gruba ait değilse çalışmıyor;

Route::get('/test', 'Test@index');

Eğerki bir gruba tayin edersem;

Route::namespace('Frontend')->group(function(){
    Route::get('/test', 'Test@index');
});

çalışıyor

**Comment by zeydo** [comment]
Test ettim bende sorun gözükmüyor.

**Comment by zeydo** [comment]
Pull request açtım oradaki router php yi dener msiniz ?

**Comment by burakbuylu** [comment]
Namespace kaynaklıymış şimdi çözdüm 👍
