### ISSUE TITLE
Facade sınıfındaki clearResolvedInstances gereksiz olabilir

### ISSUE THREAD

**Issue by irfanevrens** [tkaratug/titan2#53]
Sadece Kernel.php de initApplications kısmında çalışan ve null bir statik değişken olan $reselovedInstance değişkenini [] olarak işaretliyor. Bu $reselovedInstance statik değişkeni başlangıçta da $reselovedInstance = [] olarak işaretlenebilir. Dolayısıyla clearResolvedInstances fonksiyonununu çalıştırmaya gerek yok. 

Tabi clearResolvedInstances fonksiyonu varlığını sürdürmeye devam edebilir, ihtiyaç duyulabilecek bir şey ise bir yerlerde kullanılabilir. 

Minimum çözüm önerisi olarak;

clearResolvedInstances fonksiyon kullanımı initApplications metodu içinden kaldırılabilir. $reselovedInstance ise [] olarak işaretlenebilir default olarak.

Maximum çözüm önerisi olarak;

Yukarıdaki çözüme ek olarak clearResolvedInstances fonksiyonu da kaldırılabilir.

**Comment by tkaratug** [comment]
Haklısınız, orada clearResolvedInstances çağırmaktansa [] eşitlemek daha doğru. Gerekli düzenlemeyi yaptım. Öneriniz için teşekkürler.
