### ISSUE TITLE
Route Yapısı Bug

### ISSUE THREAD

**Issue by burakbuylu** [tkaratug/titan2#60]
Örnek kullanım:

Cont.
Route::get('/p/{username}-{id}', 'Profiles@index')->name('profile');

In View:
route('profile',['username'=>'Burti','id'=>'1234']);

Output:
/p/Burti

Olması Gereken:
/p/Burti-1234

**Comment by tkaratug** [comment]
Aslında bu bir bug değil. Her bir url segmentinde tek bir parametre olacak şekilde geliştirildi.
