### ISSUE TITLE
Public klasörüne erişme

### ISSUE THREAD

**Issue by ferdisahin** [tkaratug/titan2#61]
Merhaba, ben mi bir yerde hata yapıyorum anlamadım. Public klasörüne nasıl erişim sağlayacağız? Dökümanda get_css methodu kullanılmış. Onu denediğimde **Call to undefined function get_css()** hatası alıyorum. 

Public klasörüne nasıl erişim sağlayabiliriz?

**Comment by tkaratug** [comment]
`public_path()` fonksiyonu ile erilebilirsiniz. Dökümanı güncelleyeceğim.
