### ISSUE TITLE
Modeldeki Fonksiyona Erişemiyorum

### ISSUE THREAD

**Issue by ferdisahin** [tkaratug/titan2#62]
Merhaba, modelde şöyle bir fonskiyonum var.

`public function comments($id){
        return DB::table('comments as c')
                ->innerJoin('discussion as d', 'c.discuss_id = d.ds_id')
                ->where('d.ds_id', '=', $id)
                ->getAll();
    }`

Yani amacım yazıya ait yorum saıysını çekmek. Bunu view içerisinde gösteremiyorum. Farklı yöntemler denedim ancak başarılı olamadım. Laravel gibi değil sanırım burada olay. 

Aldığım hata şu şekilde;

> Call to undefined method stdClass::comments()

Nasıl bir yol izlemeliyim?

Bununla ilgili bir örnek var mı? Teşekkürler.

**Comment by tkaratug** [comment]
Titan'da orm yoktur. Dolayısıyla modellerin çalışma mantığı Laravel'deki gibi değildir. Aşağıdaki bağlantıdan model kullanımı ile ilgili örnekleri görebilirsiniz;
[http://v2.titanphp.com/doc/model](http://v2.titanphp.com/doc/model)

**Comment by ferdisahin** [comment]
Teşekkür ederim. Evet dökümanı çok fazla inceledim. Benim anlattığım durumla ilgili bir örnek bulamamıştım. Bu durumda söylediğim fonksiyonu nasıl çalıştırabilirim acaba?

**Comment by tkaratug** [comment]
Model facade'ını kullanarak çağırmanız gerek. Sonrasında ilgili model içerisindeki methoda erişebilirsiniz.
`Model::run('model')->comments();`
