### ISSUE TITLE
make:key Hatası

### ISSUE THREAD

**Issue by burakbuylu** [tkaratug/titan2#7]
http://prntscr.com/idw20c

**Comment by tkaratug** [comment]
Burada sonuç çıktısı renkli olduğu için sanırım cli sürümünüzde desteklenmiyor. Aşağıdaki bağlantıda gördüğünüz gibi aslında sorunsuz çalışmakta.
https://prnt.sc/idzkad

**Comment by burakbuylu** [comment]
Hocam windowsda bi sorun çıkarıyor git cli + dos + phpstorm terminal de ayni hatayi verdi bilgin olsun
