### ISSUE TITLE
/System/Libs/Event/Event.php : 32. Satır

### ISSUE THREAD

**Issue by burakbuylu** [tkaratug/titan2#9]
/System/Libs/Event/Event.php : 32. Satır üzerinde Sub array arıyor ancak mevcut değil hata veriyor.

Edit: 30. satır config dosyası yanlış yeri çekiyor;
		$listeners 	= config('Services.listeners');
olması gerekli.

**Comment by tkaratug** [comment]
Düzeltildi ve dev branch üzerine push edildi. Teşekkürler.
